/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aluraone.modules.conversor.views;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.function.DoubleUnaryOperator;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import com.aluraone.modules.conversor.services.ConversorTemperaturaService;
/**
 *
 * @author Jr
 */
public class ConversorTemperaturaView extends javax.swing.JDialog {

    private final ConversorTemperaturaService conversorTemperaturaService;
    private Map<String, DoubleUnaryOperator> conversions;
    private DecimalFormat decimalFormat;

    
    /**
     * Creates new form ConversorMonedas2View
     */
    public ConversorTemperaturaView(java.awt.Frame parent, boolean modal) {
	super(parent, modal);
	initComponents();
	conversorTemperaturaService = new ConversorTemperaturaService();
	setTitle("CONVERTIR TEMPERATURA");
	setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
	setupDecimalFormat();
	setupKeyListeners();
	setLocationRelativeTo(null); // Generar en el centro de la pantalla
	setResizable(false); // Deshabilitar la redimensión
    }
    private void setupDecimalFormat() {
	decimalFormat = new DecimalFormat("#.##");
    }

    private void setupKeyListeners() {
	txtCelsius.addKeyListener(new MyKeyListener(txtCelsius));
	txtFahrenheit.addKeyListener(new MyKeyListener(txtFahrenheit));
	txtKelvin.addKeyListener(new MyKeyListener(txtKelvin));
	txtRankine.addKeyListener(new MyKeyListener(txtRankine));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panMonedas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCelsius = new javax.swing.JTextField();
        txtFahrenheit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKelvin = new javax.swing.JTextField();
        txtRankine = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 238, 238));

        panMonedas.setBackground(new java.awt.Color(204, 204, 204));
        panMonedas.setForeground(new java.awt.Color(60, 63, 65));
        panMonedas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panMonedas.setPreferredSize(new java.awt.Dimension(220, 220));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Celsius:");

        txtCelsius.setBackground(new java.awt.Color(255, 255, 255));
        txtCelsius.setForeground(new java.awt.Color(0, 0, 0));
        txtCelsius.setToolTipText("");
        txtCelsius.setName("Celsius"); // NOI18N

        txtFahrenheit.setBackground(new java.awt.Color(255, 255, 255));
        txtFahrenheit.setForeground(new java.awt.Color(0, 0, 0));
        txtFahrenheit.setToolTipText("");
        txtFahrenheit.setName("Fahrenheit"); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fahrenheit:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Kelvin:");

        txtKelvin.setBackground(new java.awt.Color(255, 255, 255));
        txtKelvin.setForeground(new java.awt.Color(0, 0, 0));
        txtKelvin.setToolTipText("");
        txtKelvin.setName("Kelvin"); // NOI18N

        txtRankine.setBackground(new java.awt.Color(255, 255, 255));
        txtRankine.setForeground(new java.awt.Color(0, 0, 0));
        txtRankine.setToolTipText("");
        txtRankine.setName("Rankine"); // NOI18N

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Rankine:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aluraone/modules/conversor/views/images/temperature.png"))); // NOI18N

        javax.swing.GroupLayout panMonedasLayout = new javax.swing.GroupLayout(panMonedas);
        panMonedas.setLayout(panMonedasLayout);
        panMonedasLayout.setHorizontalGroup(
            panMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMonedasLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtCelsius, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(txtFahrenheit)
                    .addComponent(txtKelvin)
                    .addComponent(txtRankine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(120, 120, 120))
        );
        panMonedasLayout.setVerticalGroup(
            panMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMonedasLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(txtCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(panMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panMonedasLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(txtFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(txtKelvin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(txtRankine, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONVERSOR DE TEMPERATURA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(193, 193, 193))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(panMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(panMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private class MyKeyListener implements KeyListener {

	private final JTextField sourceField;
	private final String[] units = {"Celsius", "Fahrenheit", "Kelvin", "Rankine"};

	public MyKeyListener(JTextField sourceField) {
	    this.sourceField = sourceField;
	}

	@Override
	public void keyTyped(KeyEvent e) {
	}

	@Override
	public void keyPressed(KeyEvent e) {
	}

	@Override
	public void keyReleased(KeyEvent e) {
	    String text = sourceField.getText();
	    if (text.isEmpty()) {
		clearAllFields();
		return;
	    }

	    try {
		double value = Double.parseDouble(text);
		String sourceUnit = sourceField.getName();
		for (String targetUnit : units) {
		    if (!sourceUnit.equals(targetUnit)) {
			String conversionKey = sourceUnit + " to " + targetUnit;
			JTextField targetField = getTargetField(targetUnit);
			targetField.setText(decimalFormat.format(conversorTemperaturaService.convertTemperature(value, conversionKey)));
		    }
		}
	    } catch (NumberFormatException ex) {
		clearAllFields();
	    }
	}

	private void clearAllFields() {
	    for (String unit : units) {
		JTextField targetField = getTargetField(unit);
		targetField.setText("");
	    }
	}

	private JTextField getTargetField(String unit) {
	    switch (unit) {
		case "Celsius" -> {
		    return txtCelsius;
		}
		case "Fahrenheit" -> {
		    return txtFahrenheit;
		}
		case "Kelvin" -> {
		    return txtKelvin;
		}
		case "Rankine" -> {
		    return txtRankine;
		}
		default -> throw new IllegalArgumentException("Invalid unit");
	    }
	}
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(ConversorTemperaturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(ConversorTemperaturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(ConversorTemperaturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(ConversorTemperaturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>

	/* Create and display the dialog */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		ConversorTemperaturaView dialog = new ConversorTemperaturaView(new javax.swing.JFrame(), true);
		dialog.addWindowListener(new java.awt.event.WindowAdapter() {
		    @Override
		    public void windowClosing(java.awt.event.WindowEvent e) {
			System.exit(0);
		    }
		});
		dialog.setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panMonedas;
    private javax.swing.JTextField txtCelsius;
    private javax.swing.JTextField txtFahrenheit;
    private javax.swing.JTextField txtKelvin;
    private javax.swing.JTextField txtRankine;
    // End of variables declaration//GEN-END:variables
}
